### ISSUE TITLE
EPIC: General clean up of UI elements

### ISSUE THREAD

**Issue by andrew-cunliffe** [DashboardHub/PipelineDashboard#1051]
### Requirements

- [x] Update UI dependencies #1052
- [ ] Spacing of cards / content on UI #1053
- [ ] Fix scrolling of cards that are not held correctly in overflow #1054
- [ ] Font size override from defaults to improve readability #1055
- [x] ~~Links to main DH website #1056~~ On app add website link #1050 
- [x] Feedback button is out of place and covers footer logo #1057
